# Use Base Image
FROM openjdk:8-jdk-alpine

LABEL author="Nitendra Tech" \
      name="spark_base_image" \
      description="Base Spark Image" \
      version="v0"

# Set up the environment variables
ENV SPARK_VERSION=3.2.1
ENV HADOOP_VERSION=3.2
ENV SCALA_VERSION=2.13.0
ENV SCALA_HOME=/usr/local/scala
ENV SPARK_HOME=/usr/local/spark
ENV SPARK_OPTS --driver-java-options=-Xms1024M --driver-java-options=-Xmx4096M --driver-java-options=-Dlog4j.logLevel=info

## Update and install below utility
RUN apk --update add wget tar bash coreutils procps openssl